# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 631)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 450))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.call_tab = QtWidgets.QWidget()
        self.call_tab.setObjectName("call_tab")
        self.tabWidget.addTab(self.call_tab, "")
        self.recall_tab = QtWidgets.QWidget()
        self.recall_tab.setObjectName("recall_tab")
        self.tabWidget.addTab(self.recall_tab, "")
        self.search_tab = QtWidgets.QWidget()
        self.search_tab.setObjectName("search_tab")
        self.tabWidget.addTab(self.search_tab, "")
        self.statistics_tab = QtWidgets.QWidget()
        self.statistics_tab.setObjectName("statistics_tab")
        self.tabWidget.addTab(self.statistics_tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.menubar.setObjectName("menubar")
        self.menuLogout = QtWidgets.QMenu(parent=self.menubar)
        self.menuLogout.setObjectName("menuLogout")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOperator = QtGui.QAction(parent=MainWindow)
        self.actionOperator.setObjectName("actionOperator")
        self.actionAdmin = QtGui.QAction(parent=MainWindow)
        self.actionAdmin.setObjectName("actionAdmin")
        self.menuSettings.addAction(self.actionOperator)
        self.menuSettings.addAction(self.actionAdmin)
        self.menubar.addAction(self.menuLogout.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DrakenCC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.call_tab), _translate("MainWindow", "Call"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recall_tab), _translate("MainWindow", "Recall"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_tab), _translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statistics_tab), _translate("MainWindow", "Statistics"))
        self.label.setText(_translate("MainWindow", "DrakenCC - <a href=\"https://draken.ee\">https://draken.ee</a>"))
        self.menuLogout.setTitle(_translate("MainWindow", "Logout"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOperator.setText(_translate("MainWindow", "Operator"))
        self.actionAdmin.setText(_translate("MainWindow", "Admin"))
